### PR TITLE
don't load newcomer dinner JS without the data

### LINKED ISSUE #105: lots of unused JS on Venues page
See view-source:https://2022.code4lib.org/general-info/venues/ and scroll to the very bottom, there's a bunch of JS that's loaded for newcomers' dinner information even if that information isn't present. It comes from _includes/footer.html:

```html
{% if page.title == 'Venues' %}
<script src="https://kit.fontawesome.com/bd2d035961.js" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
<script>
  $(document).ready(function() {
    $('#dinner-datatable').DataTable({
        "paging": false,
        "searching": false,
        "autoWidth": false,
        "order": [[0, 'asc']]
        });
    } );
</script>
{% endif %}
```

We probably 1) don't want to load a slightly different version of jQuery (3.4.1 is loaded several lines above this) and 2) only want to load these assets if newcomers' dinner information exists, so the wrapping conditional could be `{% if page.title == 'Venues'  and site.data.dinner != nil %}` instead.

There's also a commented-out line `<!-- <script>window.jQuery || document.write('<script src="{{ "/assets/js/vendor/jquery-1.11.2.min.js" | relative_url }}"><\/script>')</script> -->` in footer.html that we can remove, that is a very old jQuery version.

### PR DESCRIPTION
**Pull request by phette23**
Closes #105. Mostly stops unneeded JS from being loaded but also contains a couple small improvements to newcomer dinner code & more example restaurant data. Very low priority.

**To test**:
- copy _data/examples/dinner.yml into the _data directory
- uncomment the menu items in general-info/venues/index.html 
- check that the **Restaurant List** under the Newcomer Dinner section works & makes sense http://127.0.0.1:4000/general-info/venues/#dinner

It's probably easiest to uncomment _all_ the Venues menu items. Jekyll threw an error when I uncommented only the Newcomer Dinner section, it doesn't like it if you uncomment items in the middle of an array it seems.

### CODE REVIEW

**Review by kaitlinnewson — COMMENTED** [review]
Things are displaying as expected, and I can see the JS only being loaded when the dinner data is present.

A few questions/thoughts about possible improvements to the dinner list:

- Is the tooltip beside the name keyboard accessible? It doesn't seem to be to me, but maybe I'm not using the right keyboard interaction.
- Should price point or seating of more than 6 be added to the table?
- Should there be some kind of separator between the notes and accessible notes, when both are present? I'm looking at the [2020 site](https://2020.code4lib.org/general-info/venues/#dinner) for reference, and the tooltip text is awkward when both are present (e.g. for Sienna Mercato).

**Comment by phette23** [comment]
Good questions.

It does look like the tooltip is inaccessible, I also couldn't get the text to display via keyboard. I'll have to look into it more.

For the print point and party size, how important are those? I don't mind adding more info but there's definitely a limit on how much we can feasibly put into the table. I kind of like the idea of adding price point, _combining_ the vegan and vegetarian columns into one column, and still leaving the party size off since it seems the least relevant.

For the two notes fields, it looks OK if you write them knowing they'll be next to each other, with punctuation in between. Do we need two notes fields? What about renaming and combining these into `accessibility-and-notes`? It'll be easier to use correctly if it's just one field.

**Comment by kaitlinnewson** [comment]
I think price point would be a good one to include, and agree about party size being less relevant. I think combining the notes field makes sense as well!

**Comment by phette23** [comment]
OK I made the table and data changes, PR is still a draft because I need to work on the tooltip accessibility.

**Comment by phette23** [comment]
This is ready for another review. I was confused about what was supposed to be happening with the tooltips — we load Popper.js in a script tag but it's not referenced anywhere in the code. I think we must have had some Bootstrap/jQuery applying tooltips in the past that got lost; I added one line to footer.html and they're back now.

Screen Shot 2022-03-02 at 4 47 17 PM

They are read by screenreaders, a `span.sr-only` with the `title` attribute for text content is added to the page. When I tested wit Voiceover, it read the name of the restaurant twice, but I can't figure out why. It's like the text from the element before the tooltip is prepend onto it but I don't see that in the HTML source at all. Maybe it's a VO implementation thing?

**Comment by kaitlinnewson** [comment]
The tooltips look good to me now!

A couple of last non-blocking questions:
- Is there any reason to keep "can-seat-more-than-one-group-of-6" in the example data if it's not being displayed?
- The vegan/vegetarian logic could be adjusted a little since any restaurant that is vegan friendly will be automatically vegetarian friendly.

**Comment by phette23** [comment]
Great! I left the vegan/vegetarian logic as it is after our discussion, but I suppose most people filling out the data will choose both so maybe that's silly. Depending on how the data looks, it's a simple change to fix.

I removed the unused data points and I'll go ahead and merge this.

**Pull request merged**
