### PR TITLE
speakers - better twitter link for screenreaders

### LINKED ISSUE #48: screenreader review of the speakers & past keynotes pages
This issue is a WIP. For context, I am using macOS VoiceOver with its default settings (e.g. "Navigate webpages by: DOM order"). I am working on resolving these issues on the [speaker-a11y](https://github.com/code4lib/2022.code4lib.org/tree/speaker-a11y) branch.

- [x] Twitter links are confusing because they read as only a (usually unpronounceable) username
- [x] Are the (ARIA) expanded-collapsed states needed if VO + → reads through bios anyways? (Yes, they're fine)

I need to learn more about how you're expected to navigate web content with VoiceOver to address the second point.

In our last meeting, someone mentioned that links in bios interrupt tabbing through the speakers by name. In my testing, this is the case _only when the speaker's bio is expanded_, which I think is predictable & desirable behavior. It also speaks to my second bullet point above perhaps not requiring any changes; the expanded state is useful information to know if you will tab into a bio link or not.

I have a draft PR for this now.

### PR DESCRIPTION
**Pull request by phette23**
Tell readers it's a twitter link while not repeating the username twice. Twitter usernames tend to be unreadable and simply announcing something like "link: @phette23" is not helpful. Closes #48

To test:
- apply PR
- use a screenreader (e.g. Voiceover on macOS, System Preferences > Accessibility > Voiceover. If your system doesn't have a screenreader and you don't want to install one, there are Chrome extensions too)
- visit past keynotes page /speakers/past-keynotes
- expand the bio of someone with a Twitter handle (e.g. Mega Subramaniam)
- listen to the link being read before the bio to see if it makes sense

### CODE REVIEW

**Comment by dzoladz** [comment]
Reading the twitter handle works as expected.

However, I'm running into an issue with the reading the links in collapsed bios in a specific case. Once I expand a bio with a link in it, tab to the next speaker and expanded that bio by pressing enter, if I hit shift+tab to move backwards, VO reads the link that's within the bio of the previous speaker (even though the bio is visibly hidden and collapsed). 

I'm not certain if this is a valid method to solve the issue, but updating `_speakers.scss` to specifically declare `display: none;` in the `.speaker.info` class and adding `display: flex;` to `.speaker-info.show` seems to correct it.
 
```
.speaker-info {
  -moz-transition: max-height .15s ease;
  -o-transition: max-height .15s ease;
  -webkit-flex-flow: row wrap;
  -webkit-transition: max-height .15s ease;
  background-color: $speaker-info-bg;
  border: none;
  border-radius: 5px;
  display: none;
  flex-flow: row wrap;
  justify-content: space-around;
  max-height: 0;
  overflow: hidden;
  transition: max-height .15s ease;
  width: 900px;
}

.speaker-info.show {
  -moz-transition: max-height .35s ease;
  -o-transition: max-height .35s ease;
  -webkit-transition: max-height .35s ease;
  max-height: 600px;
  transition: max-height .35s ease;
  transition-delay: .15s;
  display: flex;
}
```

**Comment by phette23** [comment]
That change works for me! Not sure why tab/shift-tab will cycle through links even when they're in collapsed content, but you're right, that does seem to be the behavior.

While we're editing _speakers.scss, do we still need all these vendor prefixed properties? CSS [transitions](https://caniuse.com/?search=transition) have great support now, and [flex-flow](https://caniuse.com/?search=flex-flow) is only a little worse.

Let me know what you think and I can add a commit onto this PR.

**Comment by dzoladz** [comment]
> do we still need all these vendor prefixed properties?

That's a good point. We probably no longer need the prefixed properties. Might as well remove them.

**Comment by phette23** [comment]
OK I just pushed your changes plus removing the vendor prefixes from that file.

**Pull request merged**
