### PR TITLE
Close: toggle t-shirt proposals to false

### LINKED ISSUE #94: Close - Shirt Logo Proposals
"The deadline to enter a design for consideration is midnight (EDT) on Friday, March 18, 2022."

### PR DESCRIPTION
**Pull request by dzoladz**
This PR simply toggles the `shirt-proposals.show`

```
shirt-proposals:
  show: false
```

Closes #94

### CODE REVIEW

**Comment by dzoladz** [comment]
@prscheduler 19/03/2022T05:00

**Comment by phette23** [comment]
Is it a concern that the PR Scheduler bot didn't comment on this PR to confirm it's scheduled? It did for the registration PR: https://github.com/code4lib/2022.code4lib.org/pull/123#issuecomment-1054607589

**Comment by dzoladz** [comment]
Sigh... I think it might be. The GitHub repo is empty: https://github.com/PR-Scheduler and the reverse proxy is returning 502 for the website https://www.prscheduler.com/

**Comment by phette23** [comment]
@prscheduler 19/03/2022T05:00

**Comment by phette23** [comment]
Hmm maybe it's just temporarily down? I thought this PR predated one of mine that successfully used it.

I tried to look around for any other news about PR Scheduler but I don't see much, no one else is talking about it being down. This is the creator on Twitter https://twitter.com/TomKadwill I'll message him.

**Comment by dzoladz** [comment]
I sent Tom an email last night too. He confirmed that the service was down, but it's back up this morning.

**Comment by dzoladz** [comment]
@prscheduler 19/03/2022T05:00

**Comment by phette23** [comment]
Yep I forgot to mention he got back to me on Twitter. Looks like this is ready now! We should probably keep an eye on all these scheduled PRs though in case the app happens to be down when a PR is scheduled to be merged.

**Pull request merged**
