### PR TITLE
Issue#4

### PR DESCRIPTION
**Pull request by metageeky**
Sorry for taking so long on implementing this, but I addressed two major issues with improving the alt text of speaker images.

1. First, I fixed the toggles to use <button> instead of <a>, which is best semantically. I also made it so that a profile will close if you click it again. That's expected behavior for a toggled disclosure such as these.

2. As I proposed, people can contribute an alt text alongside their image. I adjusted the speaker box HTML to utilize all this. If the custom alt is in speakers.yml, the alt text is assigned appropriately. If there is none, a different alt text is given. If it's a placeholder image, a different alt is given. Furthermore, if the custom alt is present, it's also shown as a description in the expanded bio. 

If this is okay, I'll work on whatever we need to collect alt text.

### CODE REVIEW

**Comment by metageeky** [comment]
Oh, to demonstrate all the ways the alt text can be processed, I added a third keynote that can easily be removed.

**Comment by dzoladz** [comment]
I added a commit to avoid seeing the broken image icon on the test speaker.

We may need to modify this update slightly. I noticed that when I visit the speaker page on my laptop, open the test speaker details, and then reduce the width of the browser window, the bio info for the test speaker appears under Crystal Lee.
Screen Shot 2022-02-07 at 9 34 40 AM

**Comment by metageeky** [comment]
@dzoladz Good catch. I'll take a look tomorrow.

**Comment by metageeky** [comment]
Took a quick look. There's a bit of a mix of flex ordering being changed oddly on resize plus I noticed a max-height issue going on too.

**Comment by metageeky** [comment]
But it is an issue on last year's page too.

**Comment by dzoladz** [comment]
Setting the speaker-info container to `max-height: max-content;` should alleviate the issue of the speaker text from getting cut off on narrow widths.

Do you think there's an issue in the JavaScript calculations in this function that may be causing the speaker info to open for the wrong speaker on narrow widths? https://github.com/code4lib/2022.code4lib.org/blob/main/assets/js/main.js#L124

**Comment by metageeky** [comment]
Multiple fixes here. 
* Max height issue fixed. 
* The flex-ordering issue was due to the breakpoints in the code not matching the breakpoints that triggered column changes. Also, the keynotes were assumed to always be at most two. That is fixed as well.
* Headings moved down a level and a single H1 added to the speakers page. 
* Logic adjusted for the alt text. If a placeholder image path is provided, it is used. If not, a random image is chosen based on the hash of the speaker's name. This is done through a JavaScript file that I had to add inline to the speakers page so that it would work in the includes

**Comment by metageeky** [comment]
@doladz I can provide a guide for writing alt text. How are speaker photos being collected? Google form? Email? I'll adjust to whatever is needed.

**Comment by dzoladz** [comment]
Pushed two commits:
- I was running into some values of `speaker.name` resulting in negative integers, so I wrapper the resultant hash with an absolute value function to avoid getting broken image references.
- Updated the example speakers.yml file to include the new attributes

**Comment by dzoladz** [comment]
> I can provide a guide for writing alt text. How are speaker photos being collected? Google form? Email? I'll adjust to whatever is needed.

@metageeky I'm not sure how this information is being collected. @Blake- might be able to provide us with some direction or insight.

**Comment by metageeky** [comment]
Looks good. I always forget about the negative issue with JS's modulo... no remainder function. Even then, it's wonky.

**Review by phette23 — APPROVED** [review]
Looks good! There's a lot going on and I didn't exhaustively review everything but all my testing turned out positive and the code made sense to me. Thanks @metageeky for doing all this!

I guess the one question I had was whether we want to display the alt text, too. I wasn't expecting that, I'm not necessarily opposed, but was just surprised to see it.

Otherwise I think this can be merged. Remember to reset the speakers data first, though.

**Comment by dzoladz** [comment]
I'll clean up the speaker data added for testing and merge this branch. 

> I guess the one question I had was whether we want to display the alt text, too. I wasn't expecting that, I'm not necessarily opposed, but was just surprised to see it.

I'm going to kick this question over to #5. For the moment, I'll add a CSS declaration to hide the alt text while we discuss... but we'll have all of the feature code available to collect and implement the profile descriptions.

**Comment by dzoladz** [comment]
> I̶'̶l̶l̶ ̶a̶d̶d̶ ̶a̶ ̶C̶S̶S̶ ̶d̶e̶c̶l̶a̶r̶a̶t̶i̶o̶n̶ ̶t̶o̶ ̶h̶i̶d̶e̶ ̶t̶h̶e̶ ̶a̶l̶t̶ ̶t̶e̶x̶t̶ ̶w̶h̶i̶l̶e̶ ̶w̶e̶ ̶d̶i̶s̶c̶u̶s̶s̶

Actually, there's no need for this step. Remove the values from `image_alt:` is sufficient.

**Pull request merged**
